batch_size: 4
num_workers: 12
lr: 2e-3
name: null
project: Music Demixing
ckpt_path: null
seed: 42

dataset_dir: data

model:
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  lr: ${lr}
  warmup_steps: 2000

datamodule:
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  dataset_dir: ${dataset_dir}

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${name}
  project: ${project}

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  log_every_n_steps: 100
  max_epochs: 500
  val_check_interval: 1300
  check_val_every_n_epoch: null
  gradient_clip_val: 1.0
  callbacks:
    - _target_: pytorch_lightning.callbacks.ModelSummary
      max_depth: 3
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: step
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: checkpoints
      filename: '{epoch:02d}-{val_loss:.2f}'
      monitor: val_loss
      save_top_k: 3
      mode: min
      save_last: True
      verbose: True
